spring.config.import=optional:file:.env[.properties]
spring.application.name=task-manager-api
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/${MYSQL_DATABASE:task_manager}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:${MYSQL_USER:task_manager}}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false
management.endpoints.web.exposure.include=health,info
spring.datasource.password=${DB_PASSWORD:${MYSQL_PASSWORD:}}
